project_path: "data"
train: "train"
test: "test"
train_semi_supervised: "train_semi_supervised"
model_path: "models"
seed: 42
kfold: true
n_splits: 5

unet:
  resnet34:
    epochs: 1000
    batch_size: 16
  metrics:
    iou:
      eps: 1
      threshold: 0.5
  loss: 
    dice_loss:
      eps: 1
      beta: 1
    mixed_loss:
      alpha: 10.0
      gamma: 2.0
  optimizer:
    adam: 
      eps: 1
      betas: [0.9, 0.999]
      lr: 0.001
  