# Paths
model_name: unet
config_path: "config/"
directory_path: "data/"
train_path: "train/"
test_path: "test/"
train_semi_supervised_path: "train_semi_supervised"
model_path: "models"
mode: "develop"

# Filenames
train_csv: "train.csv"
sweep_path: "sweep.yaml"
params_path: "test_params.yaml"

# Defaults
log: false
checkpoint: false
sweep: false
kfold: true
seed: 42
n_splits: 5
count: 3
beta: [0.9, 0.999]
mean: [0.485, 0.456, 0.406]
std: [0.229, 0.224, 0.225]
image_resize: [224, 224]
batch_size: 16
epochs: 1

# Models
unet:
  encoder_name: "resnet34"
  encoder_depth: 5
  encoder_weights: "imagenet"
  decoder_channels: [256, 128, 64, 32, 16]
  in_channels: 3
  classes: 1
  activation: "sigmoid"
  aux_params: null

unetplusplus:
  encoder_name: "resnet34"
  encoder_depth: 5
  encoder_weights: "imagenet"
  decoder_use_batchnorm: true
  decoder_channels: [256, 128, 64, 32, 16]
  decoder_attention_type: None
  in_channels: 3
  classes: 1
  activation: "sigmoid"
  aux_params: null
