# This workflow runs tests
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run python tests

on: [push, pull_request]

jobs:
  test-env:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-activate-base: false
        activate-environment: skc_env
        environment-file: conda-envs/skc_env.yaml
    - name: Check conda environment
      shell: bash -l {0}
      run: |
        conda info
        conda list
        conda config --show-sources
        conda config --show
        printenv | sort
    - name: Test with pytest
      shell: bash -l {0}
      run: |
        pwd
        export PYTHONPATH="${PYTHONPATH}:$(pwd)"
        conda activate skc_env
        pytest -v
    - name: Check wandb setup
      shell: bash -l {0}
      run: |
        conda activate skc_env
        touch config/.env

        
        echo 'project="Sartorius-Cell-Instance-Segmentation"' >> config/.env
        echo 'entity="${{secrets.ENTITY}}"' >> config/.env
        echo 'wandb_api_key=${{secrets.WANDB_API_KEY}}' >> config/.env

        echo "config/.env contents:"
        cat config/.env
        python scripts/wandb_init.py

