name: train all models

on:
  push:
    branches:
      - train-unet

jobs:
  train-unet:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Check conda environment
        shell: bash -l {0}
        run: bash workflow_scripts/check-conda-env.bash
      - name: Wandb setup
        shell: bash -l {0}
        run: |
          touch config/.env
          bash workflow_scripts/wandb-setup.bash ${{ secrets.DEVELOP_RUN_ID }}
          echo wandb_api_key=${{ secrets.WANDB_API_KEY }} >> config/train.env

      - name: Copying dataset
        shell: bash -l {0}
        run: bash workflow_scripts/copy-dataset.bash
      - name: Train
        shell: bash -l {0}
        run: |
          mkdir "models"
          conda activate skc_env
          python scripts/train.py --defaults_path config/defaults_unet.yaml
