name: test train

on:
  push:
    branches:
      - develop-train*
      - train*

jobs:
  # OFFLINE TESTS
  test-train:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Check conda environment
        shell: bash -l {0}
        run: bash workflow_scripts/check-conda-env.bash
      - name: Copying dataset
        shell: bash -l {0}
        run: bash workflow_scripts/copy-dataset.bash
      - name: Train
        shell: bash -l {0}
        run: |
          mkdir "models"
          conda activate skc_env
          python scripts/train.py --defaults_path config/test_defaults.yaml

  # WANDB IMPLEMENTATION
  test-train-wandb:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Check conda environment
        shell: bash -l {0}
        run: bash workflow_scripts/check-conda-env.bash
      - name: Wandb setup
        shell: bash -l {0}
        run: bash workflow_scripts/wandb-setup.bash ${{ secrets.DEVELOP_RUN_ID }} ${{ secrets.WANDB_API_KEY }} config/develop.env

      - name: Copying dataset
        shell: bash -l {0}
        run: bash workflow_scripts/copy-dataset.bash
      - name: Train
        shell: bash -l {0}
        run: |
          mkdir "models"
          conda activate skc_env
          python scripts/train.py --defaults_path config/test_defaults_wandb.yaml

  # SWEEP IMPLEMENTATION
  # TODO teehee
