# This workflow runs tests
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test train

on: 
  push:
    branches:
      - develop-train

jobs:
  train:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Check conda environment
      shell: bash -l {0}
      run: |
        conda info
        conda env list
        conda config --show-sources
        conda config --show
    - name: Wandb setup
      shell: bash -l {0}
      run: |
        # touch config/.env
        export WANDB_ENTITY=${{ secrets.ENTITY }}
        export WANDB_PROJECT=Sartorius-Cell-Instance-Segmentation
        export WANDB_API_KEY=${{ secrets.WANDB_API_KEY }}
    - name: Download dataset
      shell: bash -l {0}
      run: |
        export KAGGLE_USERNAME=${{ secrets.KAGGLE_USERNAME }}
        export KAGGLE_KEY=${{ secrets.KAGGLE_API_KEY }}
        printenv | sort

        kaggle competitions download -c sartorius-cell-instance-segmentation
        ls -la
        unzip sartorius-cell-instance-segmentation.zip data/
    - name: Train
      shell: bash -l {0}
      run: |
        conda activate skc_env
        python scripts/train.py --model_name=unet --log=True --params_path=config/test_params.yaml
